# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  username: mamdouh
  password: '123456789'
  pool: 5
  timeout: 5000
  host: localhost

production:
  <<: *default
  database: postgres_production
